// GENERATED CODE - DO NOT MODIFY BY HAND
// Run: flutter packages pub run build_runner build

part of 'conversion_history_model.dart';

/// Hive TypeAdapter for ConversionHistoryModel.
/// Normally generated by build_runner, provided here for zero-config compilation.
class ConversionHistoryModelAdapter extends TypeAdapter<ConversionHistoryModel> {
  @override
  final int typeId = 0;

  @override
  ConversionHistoryModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return ConversionHistoryModel(
      id: fields[0] as String,
      inputFileName: fields[1] as String,
      outputFileName: fields[2] as String,
      inputFilePath: fields[3] as String,
      outputFilePath: fields[4] as String,
      conversionTypeLabel: fields[5] as String,
      inputFileSize: fields[6] as int,
      outputFileSize: fields[7] as int,
      timestamp: fields[8] as DateTime,
      durationMs: fields[9] as int,
      success: fields[10] as bool,
      errorMessage: fields[11] as String?,
    );
  }

  @override
  void write(BinaryWriter writer, ConversionHistoryModel obj) {
    writer
      ..writeByte(12) // number of fields
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.inputFileName)
      ..writeByte(2)
      ..write(obj.outputFileName)
      ..writeByte(3)
      ..write(obj.inputFilePath)
      ..writeByte(4)
      ..write(obj.outputFilePath)
      ..writeByte(5)
      ..write(obj.conversionTypeLabel)
      ..writeByte(6)
      ..write(obj.inputFileSize)
      ..writeByte(7)
      ..write(obj.outputFileSize)
      ..writeByte(8)
      ..write(obj.timestamp)
      ..writeByte(9)
      ..write(obj.durationMs)
      ..writeByte(10)
      ..write(obj.success)
      ..writeByte(11)
      ..write(obj.errorMessage);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversionHistoryModelAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
